name: Main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
        env:
  		NODE_OPTIONS: --openssl-legacy-provider
      - name: Test
        run: npm run test
      - name: Format
        run: npm run fmtcheck
  integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup AWS Copilot
        uses: ./ # Uses an action in the root directory
      - name: Demo
        run: copilot --help
